spring.application.name=rental-service
spring.datasource.url=jdbc:postgresql://localhost:5432/rental_db
spring.datasource.username=postgres
spring.datasource.password=123123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tmdb.api.key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3MTE4ZTgwMGNjZWVhYmUxNjMzOGRhZWVlYTk2NDQ0YiIsIm5iZiI6MTY5MDM5Njc1MS4zMDU5OTk4LCJzdWIiOiI2NGMxNjg0Zjg3MWIzNDAxMWU2OTdhOGUiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.mk8wXEd-Yr_beAW2UQ6X5qJCI2B2ecDAhmrOGGd2DIk
